version: '3.9'

services:
    web-app:
        container_name: web-app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        restart: always
